# Generated by Django 4.2.7 on 2024-05-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='image')),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('hospitals', models.IntegerField()),
                ('colleges', models.IntegerField()),
            ],
        ),
    ]
